### ISSUE TITLE
Fails to print / red led blinking

### ISSUE THREAD

**Issue by brzd** [puzrin/lbprint#2]
lbprint establishes connection with the bluetooth printer PT300BT, sends the data but the printer seems to stuck on some error:
First blinks the green led when receiving data but then chnages to red blinking led, indicating an error.

Any suggestions for resolution?

**Comment by puzrin** [comment]
- Reduce font size to keep total height < 40px. Or emulate narrow tape via `-t 6`. That seems bug in PT300BT firmware. By default lbprint tries to use max posible size (> 40px).
- Replace PT300BT to Dymo PNP if you can.

**Comment by brzd** [comment]
Here is the process reproducing the problem I am having. Can't figure out if it is related to my setup or something else. I've only debugged that there is data send.

$ ./lbprint.js -v
0.1.1

$ sudo rfcomm bind 0 A0:66:10:94:D0:29 1

$ ./lbprint.js --scan
brother_ptp300bt (Brother PT-P300BT)

$ ./lbprint.js -t 9 -p brother_ptp300bt text

--> Device blinks green light to indicate receiving data --> after a while starts to blink red light. This continues until power button is pressed shortly once.

**Comment by puzrin** [comment]
`$ ./lbprint.js -t 9 -p brother_ptp300bt text`

`-t9` is `48px`, still too much. You need `-t6` as i said.

**Comment by brzd** [comment]
Yes, used -t 6 as well. There seems to be no difference with different options when reproducing the error and sent to PT300BT. And the app seems to produce the correct content when printed on display. So it works as should except for me something is not correct when data is sent to the device.

**Comment by puzrin** [comment]
Run in separate terminal:

```sh
sudo rfcomm connect 0 A0:66:10:94:D0:29 1
```

And make sure it succeeded (keep it open). Then:

```sh
./lbprint.js -t6 "text one line"
```

**Comment by brzd** [comment]
Ok, now it works!

Thank you! Excellent work. Any plans for gui or adding functionality for printing lists, csv etc. of text?

Edit: it seems to enter the error stage, yet it does print the text before that.

Edit2: It prints also the -t 12. While printing, now it doesn't even flash the green light as it start to print immediately. Now though it is stuck in the red led blinking stage. I can print again when pressed the power button shortly, but device returns to error stage after a while by itself.

**Comment by puzrin** [comment]
Yes, P300BT sucks, as you described. I strongly advise Dymo PnP instead.
