### ISSUE TITLE
Drop use of node.js canvas package.

### ISSUE THREAD

**Issue by puzrin** [puzrin/lbprint#5]
Node's canvas is very fragile and flaky. It's better to use something more solid to render texts.

For example, harfbuzz OR pango webassembly build (pure FreeType is not enougth for full kerning support and other features).

**Comment by yisibl** [comment]
You can try https://github.com/Brooooooklyn/canvas, which is more stable.

For the WASM version of harfbuzz, you can look at https://github.com/harfbuzz/harfbuzzjs

**Comment by puzrin** [comment]
Thank you for info.  harbuffjs + freetype wasm builds look the most promissing. No time for rework at current moment.

**Comment by puzrin** [comment]
Switched to `skr canvas`, now everything works

**Comment by yisibl** [comment]
Nice work!
